# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics

on:
  # Schedule updates (daily at midnight UTC)
  schedule:
    - cron: "0 0 * * 0"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    enviroment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
